[build]
  functions = "functions"
[functions."wb-koef-scheduled"]
schedule = "*/5 * * * *"

[functions."wb-koef-expired-scheduled"]
schedule = "2 0 * * *"

[functions."contest-scheduled"]
schedule = "*/3 * * * *"